image: clojure

stages:
  - build
  - test
  - deploy

before_script:
  - export LEIN_ROOT=1

build:standard:
  stage: build
  script: script/clean-build.sh

test:standard:
  stage: test
  script:
    - script/unit-test.sh
    - script/test-runtime.sh

deploy:snapshot:
  stage: deploy
  environment: snapshots
  script:
    - script/prepare-snapshot.sh
  artifacts:
    paths:
      - target/camelot*SNAPSHOT.jar
  except:
    - tags
