before_script:
  - export LEIN_ROOT=1
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_CI_PRIVATE_KEY")
  - apt-get update -y
  - apt-get install nodejs nodejs-legacy npm curl -y
  - npm install -g phantomjs-prebuilt
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - sh -c "ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts"
  - mkdir -p ~/.m2
  - sh -c "<<EOF > ~/.m2/settings.xml
<mirrors>
    <mirror>
        <id>repo1.maven.org</id>
        <name>repo1.maven.org</name>
        <url>http://repo1.maven.org/maven2</url>
        <mirrorOf>central</mirrorOf>
    </mirror>
    <mirror>
        <id>uk.maven.org</id>
        <name>uk.maven.org</name>
        <url>http://uk.maven.org/maven2</url>
        <mirrorOf>central</mirrorOf>
    </mirror>
    <mirror>
        <id>ibiblio.net</id>
        <url>http://www.ibiblio.net/pub/packages/maven2</url>
    </mirror>
</mirrors>
EOF"

build:
  image: clojure
  script:
    - script/clean-build.sh
    - lein with-profiles +test midje
    - lein doo phantom test once
    - script/setup-testdata.sh
    - script/test-runtime.sh
    - CAMELOT_DATADIR="camelot-testdata" script/test-runtime.sh
    - script/prepare-snapshot.sh
    - mkdir -p "camelot-${CI_BUILD_REF_NAME}/"
    - cp target/camelot-*.jar script/bin/camelot-desktop.sh script/bin/camelot-desktop.bat script/bin/camelot-desktop.command "camelot-${CI_BUILD_REF_NAME}/"
  artifacts:
    name: "camelot-${CI_BUILD_REF_NAME}-$(date '+%Y%m%d%H%M%S')"
    paths:
      - "camelot-${CI_BUILD_REF_NAME}/"
