image: clojure

before_script:
  - export BOOT_AS_ROOT='yes'
  - apt-get install nodejs nodejs-legacy npm curl -y
  - npm install -g phantomjs-prebuilt
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - sh -c "ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts"
  - mkdir -p ~/bin
  - curl -fsSLo ~/bin/boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
  - chmod 755 ~/bin/boot
  - export PATH="$HOME/bin:${PATH}"

stages:
  - build
  - test
  - package

compile:
  stage: build
  image: clojure
  script:
    - boot uberjar

unittest:
  stage: build
  script:
    - boot test-all

upgrade:
  stage: test
  script:
    - script/setup-testdata.sh
    - CAMELOT_DATADIR="testdata" script/test-runtime.sh

new-install:
  stage: test
  script:
    - script/test-runtime.sh

package:
  stage: package
  script:
    - mkdir -p "camelot-${CI_BUILD_REF_NAME}/"
    - script/prepare-snapshot.sh
    - cp target/camelot-*.jar script/bin/camelot-desktop.sh script/bin/camelot-desktop.bat script/bin/camelot-desktop.command "camelot-${CI_BUILD_REF_NAME}/"
  artifacts:
    name: "camelot-${CI_BUILD_REF_NAME}-$(date '+%Y%m%d%H%M%S')"
    paths:
      - "camelot-${CI_BUILD_REF_NAME}/"
