before_script:
  - export LEIN_ROOT=1
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_CI_PRIVATE_KEY")
  - apt-get update -y
  - apt-get install nodejs nodejs-legacy npm curl -y
  - npm install -g phantomjs-prebuilt
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - sh -c "ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts"

build:
  image: clojure
  script:
    - script/clean-build.sh
    - lein with-profiles +test midje
    - lein doo phantom test once
    - script/setup-testdata.sh
    - CAMELOT_DATADIR="camelot-testdata" script/test-runtime.sh
    - script/prepare-snapshot.sh
  artifacts:
    paths:
      - target/camelot-*.jar
