image: clojure

stages:
  - build
  - test
  - deploy

before_script:
  - export LEIN_ROOT=1

build:standard:
  stage: build
  script: script/clean-build.sh

test:standard:
  stage: test
  script:
    - apt-get update -y
    - apt-get install nodejs nodejs-legacy npm -y
    - npm install -g phantomjs-prebuilt
    - lein with-profiles +test midje
    - lein doo phantom test once
    - script/test-runtime.sh

deploy:snapshot:
  stage: deploy
  environment: snapshots
  script:
    - script/prepare-snapshot.sh
  artifacts:
    paths:
      - target/camelot*SNAPSHOT.jar
  except:
    - tags
