-- name: -get-all-by-survey
SELECT survey.survey_id,
       survey.survey_name,
       survey.survey_directory,
       survey.survey_created,
       survey.survey_updated,
       site.site_id,
       site.site_name,
       site.site_sublocation,
       site.site_city,
       site.site_state_province,
       site.site_country,
       site.site_area,
       site.site_created,
       site.site_updated,
       survey_site.survey_site_id,
       survey_site.survey_site_created,
       survey_site.survey_site_updated,
       taxonomy.taxonomy_id,
       taxonomy.taxonomy_species,
       taxonomy.taxonomy_genus,
       taxonomy.taxonomy_family,
       taxonomy.taxonomy_order,
       taxonomy.taxonomy_class,
       taxonomy.taxonomy_common_name,
       taxonomy.species_mass_id,
       taxonomy.taxonomy_created,
       taxonomy.taxonomy_updated,
       species_mass.species_mass_start,
       species_mass.species_mass_end,
       camera.camera_id,
       camera.camera_name,
       camera.camera_make,
       camera.camera_model,
       camera.camera_created,
       camera.camera_updated,
       trap_station.trap_station_id,
       trap_station.trap_station_name,
       trap_station.trap_station_longitude,
       trap_station.trap_station_latitude,
       trap_station.trap_station_altitude,
       trap_station.trap_station_created,
       trap_station.trap_station_updated,
       trap_station_session.trap_station_session_start_date,
       trap_station_session.trap_station_session_end_date,
       trap_station_session.trap_station_session_id,
       trap_station_session.trap_station_session_created,
       trap_station_session.trap_station_session_updated,
       trap_station_session_camera.trap_station_session_camera_id,
       trap_station_session_camera.trap_station_session_camera_created,
       trap_station_session_camera.trap_station_session_camera_updated,
       media.media_id,
       media.media_capture_timestamp,
       media.media_filename,
       media.media_format,
       media.media_created,
       media.media_updated,
       sighting.sighting_quantity,
       sighting.sighting_sex,
       sighting.sighting_lifestage,
       sighting.sighting_created,
       sighting.sighting_updated,
       photo.photo_iso_setting,
       photo.photo_exposure_value,
       photo.photo_flash_setting,
       photo.photo_fnumber_setting,
       photo.photo_orientation,
       photo.photo_resolution_x,
       photo.photo_resolution_y,
       photo.photo_created,
       photo.photo_updated
FROM survey
LEFT OUTER JOIN survey_site USING (survey_id)
LEFT OUTER JOIN site USING (site_id)
LEFT OUTER JOIN trap_station USING (survey_site_id)
LEFT OUTER JOIN trap_station_session USING (trap_station_id)
LEFT OUTER JOIN trap_station_session_camera USING (trap_station_session_id)
LEFT OUTER JOIN media USING (trap_station_session_camera_id)
LEFT OUTER JOIN sighting USING (media_id)
LEFT OUTER JOIN taxonomy USING (taxonomy_id)
LEFT OUTER JOIN camera USING (camera_id)
LEFT OUTER JOIN photo USING (media_id)
LEFT OUTER JOIN species_mass USING (species_mass_id)

-- name: -get-all-by-site
SELECT survey.survey_id,
       survey.survey_name,
       survey.survey_directory,
       survey.survey_created,
       survey.survey_updated,
       site.site_id,
       site.site_name,
       site.site_sublocation,
       site.site_city,
       site.site_state_province,
       site.site_country,
       site.site_area,
       site.site_created,
       site.site_updated,
       survey_site.survey_site_id,
       survey_site.survey_site_created,
       survey_site.survey_site_updated,
       taxonomy.taxonomy_id,
       taxonomy.taxonomy_species,
       taxonomy.taxonomy_genus,
       taxonomy.taxonomy_family,
       taxonomy.taxonomy_order,
       taxonomy.taxonomy_class,
       taxonomy.taxonomy_common_name,
       taxonomy.species_mass_id,
       taxonomy.taxonomy_created,
       taxonomy.taxonomy_updated,
       species_mass.species_mass_start,
       species_mass.species_mass_end,
       camera.camera_id,
       camera.camera_name,
       camera.camera_make,
       camera.camera_model,
       camera.camera_created,
       camera.camera_updated,
       trap_station.trap_station_id,
       trap_station.trap_station_name,
       trap_station.trap_station_longitude,
       trap_station.trap_station_latitude,
       trap_station.trap_station_altitude,
       trap_station.trap_station_created,
       trap_station.trap_station_updated,
       trap_station_session.trap_station_session_start_date,
       trap_station_session.trap_station_session_end_date,
       trap_station_session.trap_station_session_id,
       trap_station_session.trap_station_session_created,
       trap_station_session.trap_station_session_updated,
       trap_station_session_camera.trap_station_session_camera_id,
       trap_station_session_camera.trap_station_session_camera_created,
       trap_station_session_camera.trap_station_session_camera_updated,
       media.media_id,
       media.media_capture_timestamp,
       media.media_filename,
       media.media_format,
       media.media_created,
       media.media_updated,
       sighting.sighting_quantity,
       sighting.sighting_sex,
       sighting.sighting_lifestage,
       sighting.sighting_created,
       sighting.sighting_updated,
       photo.photo_iso_setting,
       photo.photo_exposure_value,
       photo.photo_flash_setting,
       photo.photo_fnumber_setting,
       photo.photo_orientation,
       photo.photo_resolution_x,
       photo.photo_resolution_y,
       photo.photo_created,
       photo.photo_updated
FROM site
LEFT OUTER JOIN survey_site USING (site_id)
LEFT OUTER JOIN survey USING (survey_id)
LEFT OUTER JOIN trap_station USING (survey_site_id)
LEFT OUTER JOIN trap_station_session USING (trap_station_id)
LEFT OUTER JOIN trap_station_session_camera USING (trap_station_session_id)
LEFT OUTER JOIN media USING (trap_station_session_camera_id)
LEFT OUTER JOIN sighting USING (media_id)
LEFT OUTER JOIN taxonomy USING (taxonomy_id)
LEFT OUTER JOIN camera USING (camera_id)
LEFT OUTER JOIN photo USING (media_id)
LEFT OUTER JOIN species_mass USING (species_mass_id)

-- name: -get-all-by-taxonomy
SELECT survey.survey_id,
       survey.survey_name,
       survey.survey_directory,
       survey.survey_created,
       survey.survey_updated,
       site.site_id,
       site.site_name,
       site.site_sublocation,
       site.site_city,
       site.site_state_province,
       site.site_country,
       site.site_area,
       site.site_created,
       site.site_updated,
       survey_site.survey_site_id,
       survey_site.survey_site_created,
       survey_site.survey_site_updated,
       taxonomy.taxonomy_id,
       taxonomy.taxonomy_species,
       taxonomy.taxonomy_genus,
       taxonomy.taxonomy_family,
       taxonomy.taxonomy_order,
       taxonomy.taxonomy_class,
       taxonomy.taxonomy_common_name,
       taxonomy.species_mass_id,
       taxonomy.taxonomy_created,
       taxonomy.taxonomy_updated,
       species_mass.species_mass_start,
       species_mass.species_mass_end,
       camera.camera_id,
       camera.camera_name,
       camera.camera_make,
       camera.camera_model,
       camera.camera_created,
       camera.camera_updated,
       trap_station.trap_station_id,
       trap_station.trap_station_name,
       trap_station.trap_station_longitude,
       trap_station.trap_station_latitude,
       trap_station.trap_station_altitude,
       trap_station.trap_station_created,
       trap_station.trap_station_updated,
       trap_station_session.trap_station_session_start_date,
       trap_station_session.trap_station_session_end_date,
       trap_station_session.trap_station_session_id,
       trap_station_session.trap_station_session_created,
       trap_station_session.trap_station_session_updated,
       trap_station_session_camera.trap_station_session_camera_id,
       trap_station_session_camera.trap_station_session_camera_created,
       trap_station_session_camera.trap_station_session_camera_updated,
       media.media_id,
       media.media_capture_timestamp,
       media.media_filename,
       media.media_format,
       media.media_created,
       media.media_updated,
       sighting.sighting_quantity,
       sighting.sighting_sex,
       sighting.sighting_lifestage,
       sighting.sighting_created,
       sighting.sighting_updated,
       photo.photo_iso_setting,
       photo.photo_exposure_value,
       photo.photo_flash_setting,
       photo.photo_fnumber_setting,
       photo.photo_orientation,
       photo.photo_resolution_x,
       photo.photo_resolution_y,
       photo.photo_created,
       photo.photo_updated
FROM taxonomy
LEFT OUTER JOIN sighting USING (taxonomy_id)
LEFT OUTER JOIN media USING (media_id)
LEFT OUTER JOIN trap_station_session_camera USING (trap_station_session_camera_id)
LEFT OUTER JOIN trap_station_session USING (trap_station_session_id)
LEFT OUTER JOIN trap_station USING (trap_station_id)
LEFT OUTER JOIN survey_site USING (survey_site_id)
LEFT OUTER JOIN site USING (site_id)
LEFT OUTER JOIN survey USING (survey_id)
LEFT OUTER JOIN camera USING (camera_id)
LEFT OUTER JOIN photo USING (media_id)
LEFT OUTER JOIN species_mass USING (species_mass_id)

-- name: -get-all-by-camera
SELECT survey.survey_id,
       survey.survey_name,
       survey.survey_directory,
       survey.survey_created,
       survey.survey_updated,
       site.site_id,
       site.site_name,
       site.site_sublocation,
       site.site_city,
       site.site_state_province,
       site.site_country,
       site.site_area,
       site.site_created,
       site.site_updated,
       survey_site.survey_site_id,
       survey_site.survey_site_created,
       survey_site.survey_site_updated,
       taxonomy.taxonomy_id,
       taxonomy.taxonomy_species,
       taxonomy.taxonomy_genus,
       taxonomy.taxonomy_family,
       taxonomy.taxonomy_order,
       taxonomy.taxonomy_class,
       taxonomy.taxonomy_common_name,
       taxonomy.species_mass_id,
       taxonomy.taxonomy_created,
       taxonomy.taxonomy_updated,
       species_mass.species_mass_start,
       species_mass.species_mass_end,
       camera.camera_id,
       camera.camera_name,
       camera.camera_make,
       camera.camera_model,
       camera.camera_created,
       camera.camera_updated,
       trap_station.trap_station_id,
       trap_station.trap_station_name,
       trap_station.trap_station_longitude,
       trap_station.trap_station_latitude,
       trap_station.trap_station_altitude,
       trap_station.trap_station_created,
       trap_station.trap_station_updated,
       trap_station_session.trap_station_session_start_date,
       trap_station_session.trap_station_session_end_date,
       trap_station_session.trap_station_session_id,
       trap_station_session.trap_station_session_created,
       trap_station_session.trap_station_session_updated,
       trap_station_session_camera.trap_station_session_camera_id,
       trap_station_session_camera.trap_station_session_camera_created,
       trap_station_session_camera.trap_station_session_camera_updated,
       media.media_id,
       media.media_capture_timestamp,
       media.media_filename,
       media.media_format,
       media.media_created,
       media.media_updated,
       sighting.sighting_quantity,
       sighting.sighting_sex,
       sighting.sighting_lifestage,
       sighting.sighting_created,
       sighting.sighting_updated,
       photo.photo_iso_setting,
       photo.photo_exposure_value,
       photo.photo_flash_setting,
       photo.photo_fnumber_setting,
       photo.photo_orientation,
       photo.photo_resolution_x,
       photo.photo_resolution_y,
       photo.photo_created,
       photo.photo_updated
FROM camera
LEFT OUTER JOIN trap_station_session_camera USING (camera_id)
LEFT OUTER JOIN trap_station_session USING (trap_station_session_id)
LEFT OUTER JOIN trap_station USING (trap_station_id)
LEFT OUTER JOIN survey_site USING (survey_site_id)
LEFT OUTER JOIN site USING (site_id)
LEFT OUTER JOIN survey USING (survey_id)
LEFT OUTER JOIN media USING (trap_station_session_camera_id)
LEFT OUTER JOIN sighting USING (media_id)
LEFT OUTER JOIN taxonomy USING (taxonomy_id)
LEFT OUTER JOIN photo USING (media_id)
LEFT OUTER JOIN species_mass USING (species_mass_id)

-- name: -get-all
SELECT survey.survey_id,
       survey.survey_name,
       survey.survey_directory,
       survey.survey_created,
       survey.survey_updated,
       site.site_id,
       site.site_name,
       site.site_sublocation,
       site.site_city,
       site.site_state_province,
       site.site_country,
       site.site_area,
       site.site_created,
       site.site_updated,
       survey_site.survey_site_id,
       survey_site.survey_site_created,
       survey_site.survey_site_updated,
       taxonomy.taxonomy_id,
       taxonomy.taxonomy_species,
       taxonomy.taxonomy_genus,
       taxonomy.taxonomy_family,
       taxonomy.taxonomy_order,
       taxonomy.taxonomy_class,
       taxonomy.taxonomy_common_name,
       taxonomy.species_mass_id,
       taxonomy.taxonomy_created,
       taxonomy.taxonomy_updated,
       species_mass.species_mass_start,
       species_mass.species_mass_end,
       camera.camera_id,
       camera.camera_name,
       camera.camera_make,
       camera.camera_model,
       camera.camera_created,
       camera.camera_updated,
       trap_station.trap_station_id,
       trap_station.trap_station_name,
       trap_station.trap_station_longitude,
       trap_station.trap_station_latitude,
       trap_station.trap_station_altitude,
       trap_station.trap_station_created,
       trap_station.trap_station_updated,
       trap_station_session.trap_station_session_start_date,
       trap_station_session.trap_station_session_end_date,
       trap_station_session.trap_station_session_id,
       trap_station_session.trap_station_session_created,
       trap_station_session.trap_station_session_updated,
       trap_station_session_camera.trap_station_session_camera_id,
       trap_station_session_camera.trap_station_session_camera_created,
       trap_station_session_camera.trap_station_session_camera_updated,
       media.media_id,
       media.media_capture_timestamp,
       media.media_filename,
       media.media_format,
       media.media_created,
       media.media_updated,
       sighting.sighting_quantity,
       sighting.sighting_sex,
       sighting.sighting_lifestage,
       sighting.sighting_created,
       sighting.sighting_updated,
       photo.photo_iso_setting,
       photo.photo_exposure_value,
       photo.photo_flash_setting,
       photo.photo_fnumber_setting,
       photo.photo_orientation,
       photo.photo_resolution_x,
       photo.photo_resolution_y,
       photo.photo_created,
       photo.photo_updated
FROM taxonomy
LEFT OUTER JOIN sighting USING (taxonomy_id)
LEFT OUTER JOIN media USING (media_id)
LEFT OUTER JOIN trap_station_session_camera USING (trap_station_session_camera_id)
LEFT OUTER JOIN trap_station_session USING (trap_station_session_id)
LEFT OUTER JOIN trap_station USING (trap_station_id)
LEFT OUTER JOIN survey_site USING (survey_site_id)
LEFT OUTER JOIN site USING (site_id)
LEFT OUTER JOIN survey USING (survey_id)
LEFT OUTER JOIN camera USING (camera_id)
LEFT OUTER JOIN photo USING (media_id)
LEFT OUTER JOIN species_mass USING (species_mass_id)
UNION
SELECT survey.survey_id,
       survey.survey_name,
       survey.survey_directory,
       survey.survey_created,
       survey.survey_updated,
       site.site_id,
       site.site_name,
       site.site_sublocation,
       site.site_city,
       site.site_state_province,
       site.site_country,
       site.site_area,
       site.site_created,
       site.site_updated,
       survey_site.survey_site_id,
       survey_site.survey_site_created,
       survey_site.survey_site_updated,
       taxonomy.taxonomy_id,
       taxonomy.taxonomy_species,
       taxonomy.taxonomy_genus,
       taxonomy.taxonomy_family,
       taxonomy.taxonomy_order,
       taxonomy.taxonomy_class,
       taxonomy.taxonomy_common_name,
       taxonomy.species_mass_id,
       taxonomy.taxonomy_created,
       taxonomy.taxonomy_updated,
       species_mass.species_mass_start,
       species_mass.species_mass_end,
       camera.camera_id,
       camera.camera_name,
       camera.camera_make,
       camera.camera_model,
       camera.camera_created,
       camera.camera_updated,
       trap_station.trap_station_id,
       trap_station.trap_station_name,
       trap_station.trap_station_longitude,
       trap_station.trap_station_latitude,
       trap_station.trap_station_altitude,
       trap_station.trap_station_created,
       trap_station.trap_station_updated,
       trap_station_session.trap_station_session_start_date,
       trap_station_session.trap_station_session_end_date,
       trap_station_session.trap_station_session_id,
       trap_station_session.trap_station_session_created,
       trap_station_session.trap_station_session_updated,
       trap_station_session_camera.trap_station_session_camera_id,
       trap_station_session_camera.trap_station_session_camera_created,
       trap_station_session_camera.trap_station_session_camera_updated,
       media.media_id,
       media.media_capture_timestamp,
       media.media_filename,
       media.media_format,
       media.media_created,
       media.media_updated,
       sighting.sighting_quantity,
       sighting.sighting_sex,
       sighting.sighting_lifestage,
       sighting.sighting_created,
       sighting.sighting_updated,
       photo.photo_iso_setting,
       photo.photo_exposure_value,
       photo.photo_flash_setting,
       photo.photo_fnumber_setting,
       photo.photo_orientation,
       photo.photo_resolution_x,
       photo.photo_resolution_y,
       photo.photo_created,
       photo.photo_updated
FROM survey
LEFT OUTER JOIN survey_site USING (survey_id)
LEFT OUTER JOIN site USING (site_id)
LEFT OUTER JOIN trap_station USING (survey_site_id)
LEFT OUTER JOIN trap_station_session USING (trap_station_id)
LEFT OUTER JOIN trap_station_session_camera USING (trap_station_session_id)
LEFT OUTER JOIN media USING (trap_station_session_camera_id)
LEFT OUTER JOIN sighting USING (media_id)
LEFT OUTER JOIN taxonomy USING (taxonomy_id)
LEFT OUTER JOIN camera USING (camera_id)
LEFT OUTER JOIN photo USING (media_id)
LEFT OUTER JOIN species_mass USING (species_mass_id)
