#!/bin/bash

SCRIPT_DIR=$(dirname "${0}")
PROJECT_DIR="${SCRIPT_DIR}/.."
DIST_DIR="${PROJECT_DIR}/dist"
TARGET_DIR="${PROJECT_DIR}/target"

${SCRIPT_DIR}/prepare-repo.sh

which lein &> /dev/null
if [ $? -ne 0 ]; then
    if [ -z $1 ]; then
        echo "[Error] lein not found in \$PATH."
        echo "If it's not installed, please install it (https://leiningen.org/). Otherwise specify the path to lein as an argument."
        exit 1
    else
        LEIN=$1
    fi
else
    LEIN=$(which lein)
fi

$LEIN uberjar
mkdir -p ${DIST_DIR}
cp ${TARGET_DIR}/camelot.jar ${DIST_DIR}/camelot-$(git describe).jar
