#!/bin/bash

set -e

if [ "$1" = "clj" ]; then
    clojure -A:test -m kaocha.runner unit "${@:2}"
elif [ "$1" = "cljs" ]; then
    npm install
    clojure -A:test -m kaocha.runner unit-cljs
else
    npm install
    clojure -A:test -m kaocha.runner unit unit-cljs "${@:2}"
fi
