#!/bin/sh

set -e

if [ "$1" = "clj" ]; then
    lein with-profiles +test,-dev test
elif [ "$1" = "cljs" ]; then
    npm install
    apt-get install firefox-esr -y
    lein with-profiles +test,-dev run -m figwheel.main -m camelot.test-runner
else
    npm install
    lein with-profiles +test,-dev test
    lein with-profiles +test,-dev run -m figwheel.main -m camelot.test-runner
fi
