(ns ctdp.exif-test-metadata
  (:require [clojure.test :refer :all]
            [ctdp.core :refer :all]))

(def maginon-metadata
  {"Compression Type" "Baseline",
   "FlashPix Version" "1.00",
   "Shutter Speed Value" "1/32 sec",
   "Custom Rendered" "Normal process",
   "Component 2"
   "Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert",
   "Software" "V3.33A",
   "Color Space" "sRGB",
   "Orientation" "Top, left side (Horizontal / normal)",
   "Image Description" "",
   "F-Number" "f/2.8",
   "File Size" "1175819 bytes",
   "Data Precision" "8 bits",
   "Aperture Value" "f/2.6",
   "White Balance Mode" "Auto white balance",
   "Date/Time Digitized" "2014:04:11 16:37:52",
   "Sensing Method" "One-chip color area sensor",
   "File Source" "Digital Still Camera (DSC)",
   "Make" "Maginon",
   "Interoperability Index"
   "Recommended Exif Interoperability Rules (ExifR98)",
   "Component 1"
   "Y component: Quantization table 0, Sampling factors 1 horiz/2 vert",
   "Interoperability Version" "1.00",
   "Scene Capture Type" "Standard",
   "ISO Speed Ratings" "600",
   "Exif Version" "2.20",
   "Metering Mode" "Center weighted average",
   "Exposure Mode" "Auto exposure",
   "Thumbnail Offset" "52368 bytes",
   "Image Width" "4000 pixels",
   "Y Resolution" "180 dots per inch",
   "Components Configuration" "YCbCr",
   "YCbCr Positioning" "Datum point",
   "Flash" "Flash did not fire, auto",
   "Date/Time" "2014:04:11 16:37:52",
   "File Name" "IMAG0001.JPG",
   "Model" "WK1",
   "Component 3"
   "Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert",
   "White Balance" "Unknown",
   "Resolution Unit" "Inch",
   "Makernote" "[51528 bytes]",
   "Image Height" "3000 pixels",
   "File Modified Date" "Fri Mar 11 09:15:15 AEDT 2016",
   "Date/Time Original" "2014:04:11 16:37:52",
   "X Resolution" "180 dots per inch",
   "Focal Length" "6.47 mm",
   "Thumbnail Length" "6520 bytes",
   "Exposure Time" "1/33 sec",
   "Number of Components" "3",
   "Exposure Program" "Program normal",
   "Exposure Bias Value" "0 EV",
   "Exif Image Width" "4000 pixels",
   "Exif Image Height" "3000 pixels",
   "Thumbnail Compression" "JPEG (old-style)",
   "Max Aperture Value" "f/2.6"})

(def cuddeback-metadata
  {"Compression Type" "Baseline",
 "Component 2"
 "Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert",
 "Software" "1187 FW 3.1.0",
 "Color Space" "sRGB",
 "Orientation" "Top, left side (Horizontal / normal)",
 "F-Number" "f/2.7",
 "File Size" "513653 bytes",
 "Data Precision" "8 bits",
 "White Balance Mode" "Auto white balance",
 "Date/Time Digitized" "2014:04:11 19:47:46",
 "Make" "CUDDEBACK",
 "Component 1"
 "Y component: Quantization table 0, Sampling factors 1 horiz/2 vert",
 "ISO Speed Ratings" "2500",
 "Exif Version" "2.21",
 "Metering Mode" "Multi-segment",
 "Image Width" "2592 pixels",
 "Y Resolution" "72 dots per inch",
 "YCbCr Positioning" "Datum point",
 "Flash" "Flash fired",
 "Date/Time" "2014:04:11 19:47:46",
 "File Name" "Cdy00003.JPG",
 "Model" "AmbushIR",
 "Component 3"
 "Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert",
 "Resolution Unit" "Inch",
 "User Comment"
 "AD=3/25/2014,RD=17,LI=7,LF=2,GH=0,BT=8,BL=5759,BP=75%,CM=Still,DY=00:00:05,CF=Disabled,IR=100%,P0=0,P1=2,P2=1,P3=3,P4=3,P5=1,P6=0,P7=0",
 "Image Height" "2000 pixels",
 "File Modified Date" "Fri Mar 11 09:35:30 AEDT 2016",
 "Date/Time Original" "2014:04:11 19:47:46",
 "X Resolution" "72 dots per inch",
 "Exposure Time" "1/250 sec",
 "Copyright" "Copyright Cuddeback, 2014",
 "Number of Components" "3",
 "Exposure Program" "Program normal",
 "Exposure Bias Value" "0 EV",
 "Exif Image Width" "2592 pixels",
 "Exif Image Height" "2000 pixels"})
