(ns camelot.util.bulk-import)

(def default-column-mappings
  {:trap-station-latitude "Camelot GPS Latitude"
   :trap-station-longitude "Camelot GPS Longitude"
   :media-capture-timestamp "Date/Time"
   :camera-make "Make"
   :camera-model "Model"
   :camera-name "Camera Name"
   :camera-notes "Camera Notes"
   :trap-station-altitude "GPS Altitude"
   :trap-station-name "Trap Station Name"
   :trap-station-session-start-date "Session Start Date"
   :trap-station-session-end-date "Session End Date"
   :trap-station-notes "Trap Station Notes"
   :site-name "Site Name"
   :site-country "Country/Primary Location Name"
   :site-state-province "Province/State"
   :site-city "City"
   :site-sublocation "Sub-location"
   :site-area "Site Area (km2)"
   :site-notes "Site Notes"
   :sighting-quantity "Sighting Quantity"
   :taxonomy-common-name "Species Common Name"
   :taxonomy-species "Species"
   :taxonomy-genus "Genus"
   :taxonomy-family "Family"
   :taxonomy-class "Class"
   :taxonomy-order "Order"
   :taxonomy-notes "Species Notes"
   :photo-fnumber-setting "Aperture Value"
   :photo-exposure-value "Exposure Bias Value"
   :photo-flash-setting "Flash"
   :photo-focal-length "Focal Length"
   :photo-iso-setting "ISO Speed Ratings"
   :photo-orientation "Orientation"
   :photo-resolution-x "Image Height"
   :photo-resolution-y "Image Width"
   :media-processed "Media Processed Flag"
   :media-cameracheck "Camera Check Flag"
   :media-attention-needed "Attention Needed Flag"})
